config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'main#index'

  resources :vehicles
  resources :customers

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
    validates :year, presence: true
    validates :make, presence: true
    validates :model, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    def index
    end

    def new
        @customer = Customer.new
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index

    end
end

app/controllers/vehicle_controller.rb
class VehicleController < ApplicationController
    def index
        @vehicles = Vehicle.all
    end

    def new
        @vehicle  = Vehicle.new
    end

    def create
        @vehicle = Vehicle.new(vehicle_params)
        if @vehicle.save
            flash[:success] = "Vehicle successfully created"
        end

        redirect_to vehicles_path
    end


    private
    def vehicle_params
        params.require(:vehicle).permit(:make, :model)
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
    def index
        @vehicles = Vehicle.all
    end

    def new
        @vehicle  = Vehicle.new
    end

    def create
        @vehicle = Vehicle.new(vehicle_params)
        if @vehicle.save
            flash[:success] = "Vehicle successfully created"
            redirect_to vehicles_path
        else
            render 'new'
        end

    end

    def show
        @vehicle = Vehicle.find(params[:id])
    end

    def edit
        @vehicle = Vehicle.find(params[:id])
    end

    def update
        @vehicle = Vehicle.find(params[:id])

        if @vehicle.update(vehicle_params)
            flash[:sucess] = "Vehicle succesfully update"
            redirect_to edit_vehicle_path
        else
            render 'edit'
        end 
    end

    private
    def vehicle_params
        params.require(:vehicle).permit(:year, :make, :model, :stock, :vin, :mileage, :color, :engine, :vehicle_type, :downPmt, :price, :weeklyPmt)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def isActive(controller, action = nil)
    if action == nil
      if params[:controller] == controller
        'active'
      elsif controller.include? params[:controller]
        'active'
      end
    elsif params[:controller] == controller && params[:action] == action
      'active'
    elsif params[:controller] == controller && (action.include? params[:action])
      'active'
    end
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/vehicle_helper.rb
module VehicleHelper
end

app/views/customers/index.html.erb
<div class="row">
    <div class="col-md">
        <h1 class="page-header">Customers</h1>
    </div>
    <div class="col-md">
        <%= link_to new_customer_path, class: "btn btn-primary float-right" do %> 
            <i class="fa fa-plus" aria-hidden="true"></i>
            Add Customer
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DMS</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav id="page-navbar" class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="#">DMS</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                  <li class="nav-item">
                      <%= link_to 'Home', root_path, class: "#{isActive 'main'} nav-link" %>
                  </li>
                  <li class="nav-item">
                      <%= link_to 'Vehicles', vehicles_path, class: "#{isActive 'vehicles'} nav-link" %>
                  </li>
                  <li class="nav-item">
                      <%= link_to 'Customers', customers_path, class: "#{isActive 'customers'} nav-link" %>
                  </li>
                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Dropdown
                      </a>
                      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <a class="dropdown-item" href="#">Action</a>
                          <a class="dropdown-item" href="#">Another action</a>
                          <div class="dropdown-divider"></div>
                          <a class="dropdown-item" href="#">Something else here</a>
                      </div>
                  </li>
              </ul>
          </div>
      </nav>
      <div class="container">
          <%= yield %>
      </div>
  </body>
</html>

app/views/main/index.html.erb
<h1>Welcome</h1>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row form-errors" style="margin-bottom: 10px;">
    <div class="col-md">
      <div class="card text-white bg-danger">
        <div class="card-body">
          <h5 class="card-title">
            <%= pluralize(obj.errors.count, "error") %> in form
          </h5>

          <ul class="card-text">
            <% obj.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/vehicle/_vehicles.html.erb
<tr>
    <td><%= vehicle.make %></td>
    <td><%= vehicle.model %></td>
</tr>

app/views/vehicle/index.html.erb
<div class="row">
    <div class="col-md">
        <h1 class="page-header">Vehicles</h1>
    </div>
    <div class="col-md">
        <%= link_to new_vehicle_path, class: "btn btn-lg rounded-circle btn-primary float-right" do %> 
            <i class="fa fa-plus" aria-hidden="true"></i>
        <% end %>
    </div>
</div>

<ul class="nav nav-tabs" style="margin-bottom: 30px">

    <li class="nav-item">
        <a class="nav-link active" href="#">Inventory</a>
    </li>
</ul>


<table class="table">
    <thead class="thead-light">
        <tr>
            <th>Make</th>
            <th>Model</th>
        </tr>
    </thead>

    <tbody>
        <% @vehicles.each do |v| %>
            <tr>
                <td><%= v.make %></td>
                <td><%= v.model %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/vehicle/new.html.erb
<h1 class="page-header">New Vehicle</h1>


<%= form_for @vehicle, url: vehicle_index_path do |f| %>
    <div class="row">

        <div class="col-md">
            <div class="form-group">
                <%= f.label :make %>
                <%= f.text_field :make, class: "form-control" %>
            </div>
        </div>
        <div class="col-md">
            <div class="form-group">
                <%= f.label :model %>
                <%= f.text_field :model, class: "form-control" %>
            </div>
        </div>

    </div>

    <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/vehicles/_form.html.erb
<%= render 'shared/errors', obj: @vehicle %>


<%= form_for @vehicle do |f| %>
    <div class="row">

        <div class="col-md">
            <div class="form-group">
                <%= f.label :year %>
                <%= f.text_field :year, class: "form-control" %>
            </div>

            <div class="form-group">
                <%= f.label :make %>
                <%= f.text_field :make, class: "form-control" %>
            </div>

            <div class="form-group">
                <%= f.label :model %>
                <%= f.text_field :model, class: "form-control" %>
            </div>
        </div>

        <div class="col-md">
            <div class="form-group">
                <%= f.label :vin, 'VIN' %>
                <%= f.text_field :vin, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= f.label :stock, "Stock#" %>
                <%= f.text_field :stock, class: "form-control" %>
            </div>

            <div class="form-group">
                <%= f.label :color %>
                <%= f.text_field :color, class: "form-control" %>
            </div>
        </div>

        <div class="col-md">
            <div class="form-group">
                <%= f.label :mileage %>
                <%= f.text_field :mileage, class: "form-control" %>
            </div>

            <div class="form-group">
                <%= f.label :engine %>
                <%= f.text_field :engine, class: "form-control" %>
            </div>

            <div class="form-group">
                <%= f.label :vehicle_type, "Vehicle Type" %>
                <%= f.text_field :vehicle_type, class: "form-control" %>
            </div>
        </div>
    </div>

    <div class="row">
             
        <div class="col-md">
            <div class="form-group">
                <%= f.label :downPmt, "Down Payment" %>
                <div class="input-group">
                    <div class="input-group-addon">$</div>
                    <%= f.text_field :downPmt, class: "form-control" %>
                </div>
            </div>
        </div>

        <div class="col-md">
            <div class="form-group">
                <%= f.label :price %>
                <div class="input-group">
                    <div class="input-group-addon">$</div>
                    <%= f.text_field :price, class: "form-control" %>
                </div>
            </div>
        </div>

        <div class="col-md">
            <div class="form-group">
                <%= f.label :weeklyPmt, "Weekly Payment" %>
                <div class="input-group">
                    <div class="input-group-addon">$</div>
                    <%= f.text_field :weeklyPmt, class: "form-control" %>
                </div>
            </div>
        </div>

    </div>

    <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/vehicles/_header.html.erb
<h1 class="margin-30 display-4"><%= @vehicle.year %> <%= @vehicle.make %> <%= @vehicle.model %></h1>

<ul class="nav nav-tabs" style="margin-bottom: 30px">
    <li class="nav-item">
        <%= link_to 'Overview', @vehicle, class: "nav-link #{isActive 'vehicles', 'show'}" %>
    </li>
    <li class="nav-item">
        <%= link_to 'Edit', edit_vehicle_path(@vehicle), class: "nav-link #{isActive 'vehicles', 'edit'}" %>
    </li>
</ul>

app/views/vehicles/_vehicle.html.erb
<tr data-link="<%= vehicle_path vehicle %>">
    <td><%= vehicle.year %></td>
    <td><%= vehicle.make %></td>
    <td><%= vehicle.model %></td>
</tr>

app/views/vehicles/edit.html.erb
<%= render 'header' %>

<%= render 'form' %>

app/views/vehicles/index.html.erb
<div class="row">
    <div class="col-md">
        <h1 class="page-header">Vehicles</h1>
    </div>
    <div class="col-md">
        <%= link_to new_vehicle_path, class: "btn btn-primary float-right" do %> 
            <i class="fa fa-plus" aria-hidden="true"></i>
            Add Vehicle
        <% end %>
    </div>
</div>

<ul class="nav nav-tabs" style="margin-bottom: 30px">
    <li class="nav-item">
        <a class="nav-link active" href="#">Inventory</a>
    </li>
</ul>


<table class="table row-links table-hover table-bordered">
    <thead class="thead-light">
        <tr>
            <th>Year</th>
            <th>Make</th>
            <th>Model</th>
        </tr>
    </thead>

    <tbody>
        <%= render @vehicles %>
    </tbody>
</table>

app/views/vehicles/new.html.erb
<h1 class="page-header">New Vehicle</h1>

<%= render 'form' %>

app/views/vehicles/show.html.erb
<%= render "header" %>

<div class="row margin-30">
    <div class="col-md">
        <div class="card text-white bg-danger mb-3" style="max-width: 20rem;">
            <div class="card-body text-center">
                <h4 class="card-title">$8,253</h4>
                <p class="card-text">total cost</p>
            </div>
        </div>
    </div>

    <div class="col-md">
        <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
            <div class="card-body text-center">
                <h4 class="card-title">23</h4>
                <p class="card-text">days on lot</p>
            </div>
        </div>
    </div>

    <div class="col-md">
        <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
            <div class="card-body text-center">
                <h4 class="card-title">10</h4>
                <p class="card-text">days on frontline</p>
            </div>
        </div>
    </div>
</div>

<h2 class="margin-30">Pricing</h2>

<div class="row">
    <div class="col-md">
        <div class="card bg-light mb-3" style="max-width: 20rem;">
            <div class="card-body text-center">
                <h4 class="card-title">$500.00</h4>
                <p class="card-text">down</p>
            </div>
        </div>
    </div>

    <div class="col-md">
        <div class="card bg-light mb-3" style="max-width: 20rem;">
            <div class="card-body text-center">
                <h4 class="card-title">$10,000.00</h4>
                <p class="card-text">price</p>
            </div>
        </div>
    </div>

    <div class="col-md">
        <div class="card bg-light mb-3" style="max-width: 20rem;">
            <div class="card-body text-center">
                <h4 class="card-title">$95.00</h4>
                <p class="card-text">weekly payment</p>
            </div>
        </div>
    </div>
</div>